version: '2'

services:
  etcd:
    image: gcr.io/google_containers/etcd:2.0.13 
    entrypoint:
      - "/usr/local/bin/etcd"
      - "-addr=127.0.0.1:4001"
      - "--bind-addr=0.0.0.0:4001"
      - "--data-dir=/var/etcd/data"
    ports:
      - "127.0.0.1:4001:4001"

#  kube-master:
#  kube-minion:

